module.exports =
{
  name : 'blok2',
  items : [
    {
      "name": "CO",
      "address": "DB10,REAL304",
      "eu": "ppm",
      "description": "CO",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "CO_RAW",
      "address": "DB10,INT302",
      "eu": null,
      "description": "CO - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "CO2",
      "address": "DB10,REAL356",
      "eu": "Vol%",
      "description": "CO2",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": 5,
      "lo": null,
      "lolo": null
    },
    {
      "name": "CO2_RAW",
      "address": "DB10,INT354",
      "eu": null,
      "description": "CO2 - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "FLOW",
      "address": "DB10,REAL148",
      "eu": "m3/s",
      "description": "FLOW",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": 1400,
      "lo": null,
      "lolo": null
    },
    {
      "name": "FLOW_RAW",
      "address": "DB10,INT146",
      "eu": null,
      "description": "FLOW - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "NOX",
      "address": "DB10,REAL200",
      "eu": "ppm",
      "description": "NOX",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": 400,
      "lo": null,
      "lolo": null
    },
    {
      "name": "NOX_RAW",
      "address": "DB10,INT198",
      "eu": null,
      "description": "NOX - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": "`",
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "O2",
      "address": "DB10,REAL408",
      "eu": "Vol%",
      "description": "O2",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "O2_RAW",
      "address": "DB10,INT406",
      "eu": null,
      "description": "O2 - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "OPACITY",
      "address": "DB10,REAL44",
      "eu": "%",
      "description": "OPACITY",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": 20,
      "lo": null,
      "lolo": null
    },
    {
      "name": "OPACITY_RAW",
      "address": "DB10,INT42.0",
      "eu": null,
      "description": "OPACITY - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "DUST",
      "address": "DB10,REAL96",
      "eu": "mg/m3",
      "description": "DUST",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "DUST_RAW",
      "address": "DB10,INT94",
      "eu": null,
      "description": "DUST - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "SO2",
      "address": "DB10,REAL252",
      "eu": "ppm",
      "description": "SO2",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    },
    {
      "name": "SO2_RAW",
      "address": "DB10,INT250",
      "eu": null,
      "description": "SO2 - Raw value",
      "scaling": false,
      "in_max": 0,
      "in_min": 10000,
      "out_max": 0,
      "out_min": 100,
      "hihi": null,
      "hi": null,
      "lo": null,
      "lolo": null
    }
  ]
} 