module.exports = {
    name : 'ion8600',
    items : [
        {
          "name": "Ia",
          "description": "Current Line A",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40150,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Ib",
          "description": "Current Line B",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40151,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Ic",
          "description": "Current Line C",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40152,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I4",
          "description": "Current Line 4",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40153,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I5",
          "description": "Current Line 5",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40154,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I_avg",
          "description": "Current Average",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40155,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I_avg_mn",
          "description": "Current Average Minimum",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40156,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I_avg_mx",
          "description": "Current Average Maximum",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40157,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I_avg_mean",
          "description": "Current Average Mean",
          "eu_desc": "Ampere",
          "eu": "A",
          "address": 40158,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Freq",
          "description": "Frequency",
          "eu_desc": "Hertz",
          "eu": "Hz",
          "address": 40159,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Freq_mn",
          "description": "Frequency Minimum",
          "eu_desc": "Hertz",
          "eu": "Hz",
          "address": 40160,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Freq_mx",
          "description": "Frequency Maximum",
          "eu_desc": "Hertz",
          "eu": "Hz",
          "address": 40161,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Freq_mean",
          "description": "Frequency Mean",
          "eu_desc": "Hertz",
          "eu": "Hz",
          "address": 40162,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "V_unbal",
          "description": "Unbalance Voltage",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40163,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "I_unbal",
          "description": "Unbalance Current",
          "eu_desc": "Ampere",
          "eu": "I",
          "address": 40164,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Phase_Rev",
          "description": "Phase Reverse",
          "eu_desc": "",
          "eu": "",
          "address": 40165,
          "type": "UInt16BE",
          "in_min": 0,
          "in_max": 60000,
          "out_min": 0,
          "out_max": 6000
        },
        {
          "name": "Vln_a",
          "description": "Voltage AN",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40166,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vln_b",
          "description": "Voltage BN",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40168,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vln_c",
          "description": "Voltage CN",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40170,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vln_avg",
          "description": "Voltage LN Average",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40172,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vln_avg_mx",
          "description": "Voltage LN Average Maximum",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40174,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Spare_1",
          "description": "Spare",
          "eu_desc": "",
          "eu": "",
          "address": 40176,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vll_ab",
          "description": "Voltage AB",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40178,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vll_bc",
          "description": "Voltage BC",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40180,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vll_ca",
          "description": "Voltage CA",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40182,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vll_avg",
          "description": "Voltage LL Average",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40184,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Vll_avg_mx",
          "description": "Voltage LL Average Maximum",
          "eu_desc": "Volt",
          "eu": "V",
          "address": 40186,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Spare_2",
          "description": "Spare 2",
          "eu_desc": "",
          "eu": "",
          "address": 40188,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Spare_3",
          "description": "Spare 3",
          "eu_desc": "",
          "eu": "",
          "address": 40190,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Spare_4",
          "description": "Spare 4",
          "eu_desc": "",
          "eu": "",
          "address": 40192,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Spare_5",
          "description": "Spare 5",
          "eu_desc": "",
          "eu": "",
          "address": 40194,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "Spare_6",
          "description": "Spare 6",
          "eu_desc": "",
          "eu": "",
          "address": 40196,
          "type": "UInt32BE",
          "in_min": 0,
          "in_max": 10000000,
          "out_min": 0,
          "out_max": 1000000
        },
        {
          "name": "kW_a",
          "description": "",
          "eu_desc": "Killo Watt",
          "eu": "kW",
          "address": 40198,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kW_b",
          "description": "",
          "eu_desc": "Killo Watt",
          "eu": "kW",
          "address": 40200,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kW_c",
          "description": "",
          "eu_desc": "Killo Watt",
          "eu": "kW",
          "address": 40202,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kW_tot",
          "description": "",
          "eu_desc": "Killo Watt",
          "eu": "kW",
          "address": 40204,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kW_tot_max",
          "description": "",
          "eu_desc": "Killo Watt",
          "eu": "kW",
          "address": 40206,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kvar_a",
          "description": "",
          "eu_desc": "Killo Volt Ampere reactive",
          "eu": "kVAr",
          "address": 40208,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kvar_b",
          "description": "",
          "eu_desc": "Killo Volt Ampere reactive",
          "eu": "kVAr",
          "address": 40210,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kvar_c",
          "description": "",
          "eu_desc": "Killo Volt Ampere reactive",
          "eu": "kVAr",
          "address": 40212,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kvar_tot",
          "description": "",
          "eu_desc": "Killo Volt Ampere reactive",
          "eu": "kVAr",
          "address": 40214,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kvar_tot_max",
          "description": "",
          "eu_desc": "Killo Volt Ampere reactive",
          "eu": "kVAr",
          "address": 40216,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVA_a",
          "description": "",
          "eu_desc": "Killo Volt Ampere",
          "eu": "kVA",
          "address": 40218,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVA_b",
          "description": "",
          "eu_desc": "Killo Volt Ampere",
          "eu": "kVA",
          "address": 40220,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVA_c",
          "description": "",
          "eu_desc": "Killo Volt Ampere",
          "eu": "kVA",
          "address": 40222,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVA_tot",
          "description": "",
          "eu_desc": "Killo Volt Ampere",
          "eu": "kVA",
          "address": 40224,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVA_tot_max",
          "description": "",
          "eu_desc": "Killo Volt Ampere",
          "eu": "kVA",
          "address": 40226,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_7",
          "description": "Spare 7",
          "eu_desc": "",
          "eu": "",
          "address": 40228,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kWh_del",
          "description": "kWh Delivered",
          "eu_desc": "Killo Watt Hour",
          "eu": "kWh",
          "address": 40230,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kWh_rec",
          "description": "KWh Received",
          "eu_desc": "Killo Watt Hour",
          "eu": "kWh",
          "address": 40232,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVARh_del",
          "description": "kVARh Delivered",
          "eu_desc": "Killo Volt Ampere Reactive Hour",
          "eu": "kVARh",
          "address": 40234,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVARh_rec",
          "description": "kVARh Received",
          "eu_desc": "Killo Volt Ampere Reactive Hour",
          "eu": "kVARh",
          "address": 40236,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "kVAh_total",
          "description": "kVAh Total",
          "eu_desc": "Killo Volt Ampere Hour",
          "eu": "kVAh",
          "address": 40238,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_8",
          "description": "Spare 8",
          "eu_desc": "",
          "eu": "",
          "address": 40240,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_9",
          "description": "Spare 9",
          "eu_desc": "",
          "eu": "",
          "address": 40242,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_10",
          "description": "Spare 10",
          "eu_desc": "",
          "eu": "",
          "address": 40244,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_11",
          "description": "Spare 11",
          "eu_desc": "",
          "eu": "",
          "address": 40246,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_12",
          "description": "Spare 12",
          "eu_desc": "",
          "eu": "",
          "address": 40248,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_13",
          "description": "Spare 13",
          "eu_desc": "",
          "eu": "",
          "address": 40250,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_14",
          "description": "Spare 14",
          "eu_desc": "",
          "eu": "",
          "address": 40252,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_15",
          "description": "Spare 15",
          "eu_desc": "",
          "eu": "",
          "address": 40254,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_16",
          "description": "Spare 16",
          "eu_desc": "",
          "eu": "",
          "address": 40256,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_17",
          "description": "Spare 17",
          "eu_desc": "",
          "eu": "",
          "address": 40258,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "Spare_18",
          "description": "Spare 18",
          "eu_desc": "",
          "eu": "",
          "address": 40260,
          "type": "Int32BE",
          "in_min": -1000000000,
          "in_max": 1000000000,
          "out_min": -1000000,
          "out_max": 1000000
        },
        {
          "name": "PF_sign_a",
          "description": "PF sign a",
          "eu_desc": "",
          "eu": "",
          "address": 40262,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "PF_sign_b",
          "description": "PF sign b",
          "eu_desc": "",
          "eu": "",
          "address": 40263,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "PF_sign_c",
          "description": "PF sign c",
          "eu_desc": "",
          "eu": "",
          "address": 40264,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "PF_sign_tot",
          "description": "PF sign tot",
          "eu_desc": "",
          "eu": "",
          "address": 40265,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "V1_THD_mx",
          "description": "V1 THD mx",
          "eu_desc": "",
          "eu": "",
          "address": 40266,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "V2_THD_mx",
          "description": "V2 THD mx",
          "eu_desc": "",
          "eu": "",
          "address": 40267,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "V3_THD_mx",
          "description": "V3 THD mx",
          "eu_desc": "",
          "eu": "",
          "address": 40268,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I1_THD_mx",
          "description": "I1 THD mx",
          "eu_desc": "",
          "eu": "",
          "address": 40269,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I2_THD_mx",
          "description": "I2 THD mx",
          "eu_desc": "",
          "eu": "",
          "address": 40270,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I3_THD_mx",
          "description": "I3 THD mx",
          "eu_desc": "",
          "eu": "",
          "address": 40271,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I1_K_Factor",
          "description": "I1 K Factor",
          "eu_desc": "",
          "eu": "",
          "address": 40272,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I2_K_Factor",
          "description": "I2 K Factor",
          "eu_desc": "",
          "eu": "",
          "address": 40273,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I3_K_Factor",
          "description": "I3 K Factor",
          "eu_desc": "",
          "eu": "",
          "address": 40274,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I1_Crest_Factor",
          "description": "I1 Crest Factor",
          "eu_desc": "",
          "eu": "",
          "address": 40275,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I2_Crest_Factor",
          "description": "I2 Crest Factor",
          "eu_desc": "",
          "eu": "",
          "address": 40276,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        },
        {
          "name": "I3_Crest_Factor",
          "description": "I3 Crest Factor",
          "eu_desc": "",
          "eu": "",
          "address": 40277,
          "type": "Int16BE",
          "in_min": -100,
          "in_max": 100,
          "out_min": -10,
          "out_max": 10
        }
      ]
}